RTOS_INC		=	FreeRTOS/FreeRTOS/Source/include \
					FreeRTOS/FreeRTOS/Source/portable/GCC/ARM_CM3


RTOS_SRCFILES	=	FreeRTOS/FreeRTOS/Source/croutine.c \
					FreeRTOS/FreeRTOS/Source/event_groups.c \
					FreeRTOS/FreeRTOS/Source/list.c \
					FreeRTOS/FreeRTOS/Source/queue.c \
					FreeRTOS/FreeRTOS/Source/stream_buffer.c \
					FreeRTOS/FreeRTOS/Source/tasks.c \
					FreeRTOS/FreeRTOS/Source/timers.c \
					FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_4.c \
					FreeRTOS/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c