RTOS_INC		=	FreeRTOS-Kernel/include \
					FreeRTOS-Kernel/portable/GCC/ARM_CM3


RTOS_SRCFILES	=	FreeRTOS-Kernel/croutine.c \
					FreeRTOS-Kernel/event_groups.c \
					FreeRTOS-Kernel/list.c \
					FreeRTOS-Kernel/queue.c \
					FreeRTOS-Kernel/stream_buffer.c \
					FreeRTOS-Kernel/tasks.c \
					FreeRTOS-Kernel/timers.c \
					FreeRTOS-Kernel/portable/MemMang/heap_4.c \
					FreeRTOS-Kernel/portable/GCC/ARM_CM3/port.c