## Переменная с файлами-зависимостями из примера

EXAMPLES_SRCFILES = common/core_clock.c \
                    common/delay.c

LIB_SRCFILES =  SPL/MDR32FxQI/src/MDR32FxQI_rst_clk.c \
				SPL/MDR32FxQI/src/MDR32FxQI_port.c \
				SPL/MDR32FxQI/src/MDR32FxQI_uart.c

# EXAMPLES_LOCAL_SRCFILES = 